#!/usr/bin/env python3
"""P1.3: relations.yaml 端点 system 上下文自动修复 + 持久化"""
import yaml
from pathlib import Path

DATA = Path('data')
rels_path = DATA / 'relations.yaml'
rels = yaml.safe_load(rels_path.read_text(encoding='utf-8'))['relations']

FIX_MAP = {
    'attributes:jin': 'spirit_roots',
    'attributes:long': 'spirit_stones',
    'spirit_beast:ling_pin': 'monsters',
    'recognition_methods:ping_deng': 'spirit_weapons',
    'realms:xian_jie': 'ascension',
    'factions:tian_ting': 'immortal_realm',
    'titles:shen_di': 'divine_realm',
    'titles:shen_min': 'divine_realm',
    'titles:xian_di': 'immortal_realm',
    'titles:san_xian': 'immortal_realm',
    'domains:tian_ting': 'divine_realm',
    'six_realms:tian_dao': 'karma',
    'six_realms:ren_dao': 'karma',
    'six_realms:xiu_luo_dao': 'underworld_realm',
    'six_realms:sheng_chu_dao': 'underworld_realm',
    'six_realms:e_gui_dao': 'underworld_realm',
    'six_realms:di_yu_dao': 'underworld_realm',
    'six_realms:a_xiu_luo': 'underworld_realm',
    'six_realms:chu_sheng': 'underworld_realm',
    'six_realms:di_yu': 'karma',
    'demon_aether:xi_mo': 'demon_realm',
    'demon_aether:mo_yuan': 'demon_realm',
    'demon_aether:pu_tong_mo': 'demon_realm',
    'demon_aether:nong_yu_mo': 'demon_realm',
    'demon_aether:hua_ye_mo': 'demon_realm',
    'demon_aether:jing_hua_mo': 'demon_realm',
    'demon_titles:mo_di': 'demon_realm',
    'demon_titles:san_mo': 'demon_realm',
    'demon_titles:mo_tu': 'demon_realm',
    'demon_titles:mo_shi': 'demon_realm',
    'demon_titles:mo_guan': 'demon_realm',
    'demon_titles:mo_jiang': 'demon_realm',
    'demon_titles:mo_jun': 'demon_realm',
    'demon_grades:fan_mo': 'demon_realm',
    'demon_grades:xian_mo': 'demon_realm',
    'demon_grades:zhen_mo': 'demon_realm',
    'demon_grades:da_mo': 'demon_realm',
    'demon_grades:zhi_mo': 'demon_realm',
    'demon_grades:dao_mo': 'demon_realm',
    'demon_tribulations:shi_xin_jie': 'demon_realm',
    'demon_tribulations:tian_mo_jie': 'demon_realm',
    'demon_tribulations:xue_mo_jie': 'demon_realm',
    'demon_tribulations:yu_mo_jie': 'demon_realm',
    'demon_tribulations:xin_mo_jie': 'demon_realm',
    'demon_races:ren_zu_mo': 'demon_realm',
    'demon_ascension:voluntary_demon': 'demon_realm',
    'demon_ascension:forced_demon': 'demon_realm',
    'demon_ascension:xian_ren_betray': 'demon_realm',
    'demon_ascension:mo_di_reincarnation': 'demon_realm',
    'underworld_titles:ming_di': 'underworld_realm',
    'underworld_titles:you_hun': 'underworld_realm',
    'underworld_titles:gui_tu': 'underworld_realm',
    'underworld_titles:gui_shi': 'underworld_realm',
    'underworld_titles:gui_guan': 'underworld_realm',
    'underworld_titles:gui_jiang': 'underworld_realm',
    'underworld_titles:gui_jun': 'underworld_realm',
    'underworld_tribulations:wan_hun_shi_xin_jie': 'underworld_realm',
    'underworld_tribulations:yin_huo_jie': 'underworld_realm',
    'underworld_tribulations:tian_lei_yin_jie': 'underworld_realm',
    'underworld_tribulations:lun_hui_jie': 'underworld_realm',
    'underworld_races:gui_zu': 'underworld_realm',
    'underworld_races:pan_guan_zu': 'underworld_realm',
    'underworld_domains:feng_du': 'underworld_realm',
    'underworld_domains:liu_dao_lun_hui_si': 'underworld_realm',
    'underworld_aether:si_yuan': 'underworld_realm',
    'barrier_types:sealed': 'ascension',
    'ascension_tribulation:ascension_tribulation': 'ascension',
    'paths:bei_pai': 'ascension',
    'ascension_types:evil': 'ascension',
    'shen_tong:zi_dian_shen_lei': 'combat',
    'shen_tong:wan_xiang_tian_yin': 'combat',
    'shen_tong:zhu_shen_jian_jue': 'combat',
    'shen_tong:hun_yuan_shen_li': 'combat',
    'shen_tong:huo_yan_quan': 'combat',
    'dun_shu:jin_dun': 'combat',
    'dun_shu:shui_dun': 'combat',
    'dun_fa:kong_jian_tiao_yue': 'combat',
    'dun_fa:shi_jian_ning_lan': 'combat',
    'fa_xiang:jin_gang_fa_xiang': 'combat',
    'fa_xiang:qing_lian_fa_xiang': 'combat',
    'ling_yu:lie_huo_yu': 'combat',
    'concentrations:xi_bao': 'aether',
    'concentrations:hua_ye_ji': 'aether',
    'concentrations:ling_ye_cheng': 'aether',
    'concentrations:tian_ti': 'aether',
    'veins:chao_ji_lingmai': 'aether',
    'veins:feng_xue_lingmai': 'aether',
    'veins:qi_lin_xue_lingmai': 'aether',
    'counter_elixirs:ji_kong_dan': 'heart_demons',
    'counter_elixirs:wu_ruo_dan': 'heart_demons',
    'counter_elixirs:duan_yu_dan': 'heart_demons',
    'types:chi_mo': 'heart_demons',
    'types:shi_mo': 'heart_demons',
    'types:quan_mo': 'heart_demons',
    'types:sheng_mo_x': 'heart_demons',
    'types:ming_mo': 'heart_demons',
    'types:li_mo': 'heart_demons',
    'law_levels:zhi_gao': 'time_space',
    'law_levels:chao_yue': 'time_space',
    'law_levels:gao_ji': 'time_space',
    'time_powers:cha_na_yong_heng': 'time_space',
    'time_powers:guang_yin_ni_zhuan': 'time_space',
    'space_powers:kong_jian_shun_yi': 'time_space',
    'space_powers:kong_jian_min_jie': 'time_space',
    'space_artifacts:kong_jian_shi': 'time_space',
    'time_artifacts:shi_guang_sha': 'tian_cai',
    'realms:kong_jian_luan_liu': 'time_space',
    'realms:xu_kong': 'time_space',
    'realms:shi_guang_he': 'time_space',
    'masters:shi_kong_dao_ren': 'time_space',
    'masters:xiao_yao_xian_di': 'time_space',
    'masters:shi_kong_zu_shen': 'time_space',
    'merit_levels:da_gong_de': 'karma',
    'merit_levels:yuan_man_gong_de': 'karma',
    'karma_levels:da_e_ye': 'karma',
    'karma_levels:ji_e_ye': 'karma',
    'karmic_obsructions:xiu_xing_zhang': 'karma',
    'karmic_obsructions:zhi_hui_zhang': 'karma',
    'solutions:chan_hui': 'karma',
    'solutions:chi_zhou': 'karma',
    'solutions:xing_shan': 'karma',
    'divine_powers:yin_guo_zhi_yan': 'karma',
    'divine_powers:gong_de_jin_shen': 'karma',
    'divine_powers:yin_guo_lun_hui': 'karma',
    'divine_powers:yin_guo_ni_zhuan': 'karma',
    'spirit_stones:xian_jing': 'immortal_realm',
    'spirit_stones:shen_jing': 'divine_realm',
    'aether:nong_yu_shen': 'divine_realm',
    'aether:dao_qi': 'divine_realm',
    'aether:jing_hua_shen': 'divine_realm',
    'tribulations:lei_shen_jie': 'divine_realm',
    'tribulations:huo_shen_jie': 'divine_realm',
    'tribulations:fu_he_shen_jie': 'divine_realm',
    'tribulations:xin_mo_shen_jie': 'divine_realm',
    'ascension_types:ordinary_ascension': 'divine_realm',
    'ascension_types:talented_ascension': 'divine_realm',
    'divine_grades:fan_ren': 'divine_realm',
    'divine_grades:zhi_shen': 'divine_realm',
    'divine_grades:dao_zu_ge': 'divine_realm',
    'immortal_tribulations:lei_xian_jie': 'immortal_realm',
    'immortal_tribulations:tian_lei_xian_jie': 'immortal_realm',
    'immortal_tribulations:jian_jin_xian_jie': 'immortal_realm',
    'techniques:tian_yan_xian_dian': 'immortal_realm',
    'techniques:jiu_zhuan_xuan_xian_jue': 'immortal_realm',
    'examples:jiu_xiao_lei_zhen': 'formations',
    'examples:tian_long_shan': 'factions',
    'examples:huo_yan_dong': 'factions',
    'examples:tian_shan_school': 'factions',
    'examples:tai_yi_gong': 'factions',
    'examples:ji_yin_si': 'factions',
    'examples:qing_lian_jian_zong': 'factions',
    'examples:tian_xia_shan': 'factions',
    'examples:mo_jiao': 'factions',
    'examples:ming_jiao': 'factions',
    'examples:zhu_que_men': 'factions',
    'examples:wan_yao_lin': 'factions',
    'examples:qi_lin_ting': 'factions',
    'examples:feng_huang_ling': 'factions',
    'examples:feng_huang': 'monsters',
    'examples:qi_lin': 'monsters',
    'examples:jin_chi_da_peng': 'monsters',
    'examples:chi_mu_mo_yuan': 'monsters',
    'examples:san_tou_di_yu_quan': 'monsters',
    'examples:yun_du_jian_he': 'monsters',
    'forms:long_xing': 'yao_xiu',
    'forms:feng_xing': 'yao_xiu',
    'stages:hua_long_jing': 'yao_xiu',
}

fixed_count = 0
for r in rels:
    for side in ('from', 'to'):
        s = r.get(side, '')
        if s in FIX_MAP:
            sys_, id_ = s.split(':', 1)
            r[side] = f'{FIX_MAP[s]}:{id_}'
            fixed_count += 1

yaml.dump({'relations': rels}, rels_path.open('w', encoding='utf-8'),
          allow_unicode=True, sort_keys=False, default_flow_style=False)
print(f'本次批量修复: {fixed_count} 条')
